/*generating rensponsive nav.
while this function is excuted, then the class "nav" from the index.html will become "class=nav responsive"
and so the .responsive in the css will activate*/
function myButton() {
	var x = document.getElementById("myNav");
	
	if (x.className === "nav") { x.className += " responsive";}
	else { x.className = "nav";}

}

/* Make higlights for the menu/page that users are on it*/
document.getElementById("Menu1").addEventListener("click", function() {
	document.getElementById("displayMenu").innerHTML = document.getElementById("Menu1").innerText
});
document.getElementById("Menu2").addEventListener("click", function() {
	document.getElementById("displayMenu").innerHTML = document.getElementById("Menu2").innerText
});
document.getElementById("Menu3").addEventListener("click", function() {
	document.getElementById("displayMenu").innerHTML = document.getElementById("Menu3").innerText
});
document.getElementById("Menu4").addEventListener("click", function() {
	document.getElementById("displayMenu").innerHTML = document.getElementById("Menu4").innerText
});
document.getElementById("Menu5").addEventListener("click", function() {
	document.getElementById("displayMenu").innerHTML = document.getElementById("Menu5").innerText
});
document.getElementById("Menu6").addEventListener("click", function() {
	document.getElementById("displayMenu").innerHTML = document.getElementById("Menu6").innerText
});

/*this window event is supposed to hide navigation (remove the "responsive" class generated by js) 
while user click the page. 
Thanks to: <a href="facebook.com/qqhgs>Ilham Bahtiar</>; for helping me get this nice event done*/
window.addEventListener('click', e => {
	const x = document.querySelector('#myNav');
	if (!x.contains(e.target) && x.classList.contains('responsive')) {
		x.classList.remove('responsive');
		}
	})

/*this is to welcome user using alert by determining what time in their browser and few language support*/
var time = new Date().getHours(); 
var greetTime = "";
  
 	switch(time) {
  		case (time < 10): 
   	greetTime = ["Good morning", "Selamat pagi", "Доброе утро", "صباح الخير"];
  		break;
  		case (time < 14):
   	greetTime = ["Good day", "Selamat siang", "Добрый день", "مساء الخير"];
   	break;
  		case (time < 16):
   	greetTime = ["Good afternoon", "Selamat sore", "Добрый день", "مساء الخير" ];
   	break;
  		case (time < 21):
   	greetTime = ["Good evening", "Selamat malam", "Добрый вечер", "مساء الخير"];
   	break;
  		default: 
   	greetTime = ["Good night", "Selamat malam", "Спокойной ночи", "تصبح على خير"];
	}
	
	var language = window.navigator.userLanguage || window.navigator.language;
	if (language === "en"||language === "en-US") {
	greetLang = greetTime[0];
	} else if (language === "id"||language === "id-ID") {
	greetLang = greetTime[1];
	} else if (language === "ru"||language === "ru-RU") {
	greetLang = greetTime[2];
	} else if (language === "ar"||language === "ar-SA") {
	greetLang = greetTime[3];
	}

  		const greeting = greetLang;
  
alert(greeting)
