/*generating rensponsive nav.
while this function is excuted, then the class "nav" from the index.html will become "class=nav responsive"
and so the .responsive in the css will activate*/
function myButton() {
	var x = document.getElementById("myNav");

	if (x.className === "nav") { x.className += " responsive";}
	else { x.className = "nav";}

}

/* Make higlights for the menu/page that users are on it
document.getElementById("Menu1").addEventListener("click", function() {
	document.getElementById("displayMenu").innerHTML = document.getElementById("Menu1").innerText
});
document.getElementById("Menu2").addEventListener("click", function() {
	document.getElementById("displayMenu").innerHTML = document.getElementById("Menu2").innerText
});
document.getElementById("Menu3").addEventListener("click", function() {
	document.getElementById("displayMenu").innerHTML = document.getElementById("Menu3").innerText
});
document.getElementById("Menu4").addEventListener("click", function() {
	document.getElementById("displayMenu").innerHTML = document.getElementById("Menu4").innerText
});
document.getElementById("Menu5").addEventListener("click", function() {
	document.getElementById("displayMenu").innerHTML = document.getElementById("Menu5").innerText
});
document.getElementById("Menu6").addEventListener("click", function() {
	document.getElementById("displayMenu").innerHTML = document.getElementById("Menu6").innerText
});
*/

/*this window event is supposed to hide navigation (remove the "responsive" class generated by js)
while user click the page.
Thanks to: <a href="facebook.com/qqhgs>Ilham Bahtiar</>; for helping me get this nice event done*/
window.addEventListener('click', e => {
	const x = document.querySelector('#myNav');
	if (!x.contains(e.target) && x.classList.contains('responsive')) {
		x.classList.remove('responsive');
		}
	})
